language: scala
os: linux
dist: xenial

jobs:
  include:
    - stage: compile
      os: linux
      name: "Compile & Formatting Check"
      env:
        - TEST_COMMAND="test:compile scalafmtCheck test:scalafmtCheck"
      scala: 2.13.3

# These directories are cached to S3 at the end of the build
# https://www.scala-sbt.org/1.x/docs/Travis-CI-with-sbt.html#Caching
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.m2

# https://www.scala-sbt.org/1.x/docs/Travis-CI-with-sbt.html#Caching
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

before_script:
  - git fetch --tags
  - git submodule sync

stages:
  - name: compile

script:
  # Modify PATH to include binaries we are about to download
  - sbt ++$TRAVIS_SCALA_VERSION $TEST_COMMAND
