# taken and modified from https://github.com/philen/scala-jpackage-workflow-demo
# jpackage docs:  https://docs.oracle.com/en/java/javase/14/docs/specs/man/jpackage.html
# jpackage jep: https://openjdk.java.net/jeps/392
name: Build for Release

on:
  push:
    branches: [ master, main]
    tags: [ "*" ]

env:
  pkg-assembly: 'krystal-bull-assembly-0.1.jar'
  pkg-name: 'krystalbull'

jobs:
  osx:
    runs-on: [macos-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.15.0-2
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
      - name: Import developer cert to keychain
        uses: apple-actions/import-codesign-certs@v1
        with:
          create-keychain: true
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
          keychain-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
      - name: Build fat jar
        run: sbt assembly
      - name: Add cert to keychain and unlock keychain & build and sign dmg
        env:
          pkg-version: ${{steps.previoustag.outputs.tag}}
          MACOS_CERTIFICATE_PWD: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
          MAC_NOTARIZATION_PW: ${{secrets.MAC_NOTARIZATION_PW}}
        # Steps to build a fully signed and notarized krystal bull dmg
        # 1. Unlock the OS x keychain so we don't have to input passwords via GUI prompts
        # 2. Build krystalbull.app that is recursively signed with jpackage --mac-sign
        # 3. Build an unsigned dmg that contains krystalbull.app inside of it (no idea why --mac-sign doesn't work with --type dmg)
        # 4. Sign the dmg with codesign (jpackage dmg signing is broken for some reason)
        # 5. Submit the dmg to apple's notarization service so can get it whitelisted for installation (see: https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution)
        # 6. Sleep until apple notorization is done
        # 7. Retrieve the signature and staple it to the dmg to so network requests do not need to be made to open the dmg
        # 8. Check all signatures on krystalbull.app (see: https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087735)
        # 9. Check all dmg signatures
        # 10. Display information about signed dmg
        run: |
          echo "Hello world"
          java -version
          jpackage --version
          ls -l
          security unlock-keychain -p $MACOS_CERTIFICATE_PWD signing_temp.keychain
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $MACOS_CERTIFICATE_PWD signing_temp.keychain
          echo "===========jpackage app image begin================"
          jpackage --verbose --name ${{ env.pkg-name }} --app-version ${{ env.pkg-version }} --mac-package-name ${{ env.pkg-name }} --type app-image -i target/scala-2.13/ --main-class com.krystal.bull.gui.GUI --main-jar ${{ env.pkg-assembly }} --icon src/main/resources/icons/krystal_bull.icns --mac-sign --mac-signing-keychain /Users/runner/Library/Keychains/signing_temp.keychain-db --mac-signing-key-user-name "Chris Stewart (9ZG3GPKHX8)"
          echo "===========jpackage dmg begin================"
          jpackage --verbose --name ${{ env.pkg-name }} --app-version ${{ env.pkg-version }} --mac-package-name ${{ env.pkg-name }} --type dmg --app-image krystalbull.app --mac-sign --mac-signing-keychain /Users/runner/Library/Keychains/signing_temp.keychain-db --mac-signing-key-user-name "Chris Stewart (9ZG3GPKHX8)"
          echo "Signing dmg with code sign"
          codesign -s "Developer ID Application: Chris Stewart (9ZG3GPKHX8)" --options runtime -vvvv --deep ${{ env.pkg-name }}-${{ env.pkg-version }}.dmg
          REQUEST_UUID=$(xcrun altool --notarize-app --primary-bundle-id "com.krystal.bull" --username "stewart.chris1234@gmail.com" --password "$MAC_NOTARIZATION_PW"  --file ${{ env.pkg-name }}-${{ env.pkg-version }}.dmg | grep RequestUUID | awk '{print $3}')
          echo "Waiting for notarization from Apple for $REQUEST_UUID"
          sleep 5
          xcrun altool --notarization-info "$REQUEST_UUID" -u "stewart.chris1234@gmail.com" -p "$MAC_NOTARIZATION_PW"
          echo "Start while loop"
          while xcrun altool --notarization-info "$REQUEST_UUID" -u "stewart.chris1234@gmail.com" -p "$MAC_NOTARIZATION_PW" | grep "Status: in progress" > /dev/null; do
            echo "Verification in progress..."
            sleep 30
          done
          xcrun stapler staple ${{ env.pkg-name }}-${{ env.pkg-version }}.dmg
          echo "Done stapling"
          spctl -vvv --assess --type exec krystalbull.app
          echo "Done inspecting app with spctl"
          codesign -vvv --deep --strict ${{ env.pkg-name }}-${{ env.pkg-version }}.dmg
          echo "Done verifying code signing deep"
          codesign -dvv ${{ env.pkg-name }}-${{ env.pkg-version }}.dmg
          echo "Done verifying artifacts"
          ls -l
      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}
      - name: Upload dmg
        uses: actions/upload-artifact@v1
        with:
          name: "krystal-bull-dmg-${{steps.previoustag.outputs.tag}}-${{github.sha}}"
          path: ${{ env.pkg-name }}-${{steps.previoustag.outputs.tag}}.dmg
  windows:
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11.0-1
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
      - name: Build msi
        shell: bash
        run: sbt windows:packageBin
      - name: View artifacts
        run: ls -R .
      - name: Upload installer
        uses: actions/upload-artifact@v1
        with:
          name: krystal-bull-msi-${{steps.previoustag.outputs.tag}}-${{github.sha}}
          path: "D:\\a\\krystal-bull\\krystal-bull\\target\\windows\\krystal-bull.msi"
  linux:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.15.0-2
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
      - name: Build fat jar
        run: sbt assembly
      - name: Package jar as debian package
        env:
          pkg-version: ${{steps.previoustag.outputs.tag}}
        run: "jpackage --linux-shortcut --name ${{ env.pkg-name }} --app-version ${{ env.pkg-version }} --type deb -i target/scala-2.13/ --main-class com.krystal.bull.gui.GUI --main-jar ${{ env.pkg-assembly }} --icon src/main/resources/icons/krystal_bull.png"
      - name: View Artifacts
        run: ls -l
      - name: Print working dir
        run: pwd
      - name: Upload deb
        uses: actions/upload-artifact@v1
        env:
          pkg-version: ${{steps.previoustag.outputs.tag}}
        with:
          name : "krystal-bull-deb-${{steps.previoustag.outputs.tag}}-${{github.sha}}"
          path: "${{ env.pkg-name }}_${{ env.pkg-version }}-1_amd64.deb"
